### PR TITLE
Remove address, fix ClassNumber bug

### LINKED ISSUE #62: Delete Address class
We do not need it anymore

### LINKED ISSUE #89: Fix class number exception bug
Exception isn't caught properly and is outputted in the console when error with class number formatting

### PR DESCRIPTION
**Pull request by Nano-233**
Closes #89, Closes #62

### CODE REVIEW

**Comment by Nano-233** [comment]
Coverage check can be ignored. Comes from multiline array initialization of testing utilities.

File: src/main/java/tassist/address/logic/commands/ClassCommand.java [hunk 1]
```diff
@@ -26,12 +26,16 @@ public class ClassCommand extends Command {
...
+            + PREFIX_CLASS + " T + [Tutorial Class Number xx (xx = 01-99)]\n"
             + "Example: " + COMMAND_WORD + " 1 "
             + PREFIX_CLASS + " T01";
 
     public static final String MESSAGE_ADD_CLASS_SUCCESS = "Assigned tutorial class to student: %1$s";
     public static final String MESSAGE_REMOVE_CLASS_SUCCESS = "Removed tutorial class from student: %1$s";
+    public static final String MESSAGE_INVALID_CLASS =
+            "Class numbers should be either 'No tutorial assigned'\n"
+                    + "            + or of the format 'Txx' (where xx is 01-99).\n"
+                    + "            + 'T' must be capitalized.";
```
Comment (Kkenjji) [inline src/main/java/tassist/address/logic/commands/ClassCommand.java:38]: There seems to be random indentations, I assume it's typo.

**Review by Kkenjji — CHANGES_REQUESTED** [review]

**Review by Casielim — APPROVED** [review]
Looks good to me!🤓

**Review by Kkenjji — APPROVED** [review]
LGTM
