### PR TITLE
Branch make name strictly numerical

### LINKED ISSUE #299: [PE-D][Tester B] Students name can be numbers
Students name can be just numbers

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jaylontan/ped#6

### LINKED ISSUE #323: [PE-D][Tester A] Unable to find a student whose name is T01
## Description
Unable to find a student whose name is T01. Original intention is to find the name of T01 but it instead lists out the people from T01

## Steps to reproduce
`edit 1 n/T01`
`edit 2 c/T01`
`edit 1 c/T02`
`find T01` (finding the name T01)
(Only student 2 is in T01)

## Expected
The student with the name T01 appears

## Actual
Finds student number 2

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: aquaimpact/ped#8

### PR DESCRIPTION
**Pull request by elizazaa**
Closes #299 
Closes #323

### CODE REVIEW

**Review by Kkenjji — APPROVED** [review]
LGTM

File: src/test/java/tassist/address/model/person/NameTest.java [hunk 1]
```diff
@@ -26,16 +26,18 @@ public void isValidName() {
...
 
         // valid name
         assertTrue(Name.isValidName("peter jack")); // alphabets only
-        assertTrue(Name.isValidName("12345")); // numbers only
-        assertTrue(Name.isValidName("peter the 2nd")); // alphanumeric characters
+        assertTrue(Name.isValidName("peter rose II")); // addition of II (for numerals)
         assertTrue(Name.isValidName("Capital Tan")); // with capital letters
-        assertTrue(Name.isValidName("David Roger Jackson Ray Jr 2nd")); // long names
+        assertTrue(Name.isValidName("David Roger Jackson Ray Jr II")); // long names
+        assertTrue(Name.isValidName("David Son Of Deshaka")); // addition of 'son of'
```
Comment (crmlatte) [inline src/test/java/tassist/address/model/person/NameTest.java:40]: nice updates to tests

File: src/main/java/tassist/address/model/person/Name.java [hunk 2]
```diff
@@ -10,13 +10,13 @@
...
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names should only contain alphabetic characters and should not be blank";
 
     /**
-     * The first character of the address must not be a whitespace,
+     * The first character of the name must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid input.
      */
-    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} ]*";
+    public static final String VALIDATION_REGEX = "[a-zA-Z][a-zA-Z ]*";
```
Comment (crmlatte) [inline src/main/java/tassist/address/model/person/Name.java:19]: good changes

**Review by crmlatte — APPROVED** [review]
lgtm
