### PR TITLE
Fix list filtering using ProjectTeam

### LINKED ISSUE #166: Fix list filtering using ProjectTeam

### PR DESCRIPTION
**Pull request by elizazaa**
Closes #166

### CODE REVIEW

File: src/test/java/tassist/address/logic/commands/ListCommandTest.java [hunk 1]
```diff
@@ -154,33 +154,35 @@ public void execute_filteredByTeamNoMatch_returnsNoStudents() {
...
 
         Predicate<Person> expectedPredicate = person ->
-                person.getProjectTeam() != null && person.getProjectTeam().value.equalsIgnoreCase("nonexistentTeam");
+                person.getProjectTeam().value.equalsIgnoreCase("nonexistentTeam");
 
         expectedModel.updateFilteredPersonList(expectedPredicate);
 
         assertCommandSuccess(command, model, ListCommand.MESSAGE_NO_STUDENTS, expectedModel);
-
     }*/
```
Comment (Casielim) [inline src/test/java/tassist/address/logic/commands/ListCommandTest.java:162]: Can remove this test, it's duplicate, is the same as execute_filteredByTeamInvalidValue_throwsCommandException()

File: src/test/java/tassist/address/logic/commands/ListCommandTest.java [hunk 2]
```diff
@@ -154,33 +154,35 @@ public void execute_filteredByTeamNoMatch_returnsNoStudents() {
...
     }
 
     @Test
     public void execute_filteredByProgressInvalidValue_throwsCommandException() {
         ListCommand command = new ListCommand(null, null, "progress", "invalidValue");
         CommandException thrown = assertThrows(CommandException.class, () -> command.execute(model));
-        assertEquals(ListCommand.MESSAGE_INVALID_FILTER_VALUE, thrown.getMessage());
+        String message = String.format(ListCommand.MESSAGE_NONEXISTENT_FILTER_VALUE, command.filterValue);
+        assertEquals(message, thrown.getMessage());
     }
```
Comment (Casielim) [inline src/test/java/tassist/address/logic/commands/ListCommandTest.java:186]: can keep the message_invalid_filter_value here.

**Review by Casielim — CHANGES_REQUESTED** [review]
Just a few tweaks, thanks!

**Review by Casielim — APPROVED** [review]
LGTM😁

**Review by Nano-233 — APPROVED** [review]
LGTM
