### PR TITLE
Fix duplication check logic of Github

### LINKED ISSUE #337: "No Github Assigned" is considered as duplicate github.
Image

### PR DESCRIPTION
**Pull request by Nano-233**
Closes #337 
Default github is no longer checked as a duplicate

### CODE REVIEW

File: src/main/java/tassist/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -111,7 +111,8 @@ public CommandResult execute(Model model) throws CommandException {
             if (p.getEmail().equals(editedPerson.getEmail())) {
                 throw new CommandException(MESSAGE_EXISTING_EMAIL);
             }
-            if (p.getGithub().equals(editedPerson.getGithub())) {
+            if (!editedPerson.getGithub().value.equals("no github assigned")
```
Comment (crmlatte) [inline src/main/java/tassist/address/logic/commands/EditCommand.java:114]: Shld be upper case!
```suggestion
            if (!editedPerson.getGithub().value.equals("No Github assigned")
```

File: src/main/java/tassist/address/logic/commands/AddCommand.java [hunk 2]
```diff
@@ -82,7 +82,8 @@ public CommandResult execute(Model model) throws CommandException {
                 .anyMatch(person -> person.getEmail().equals(toAdd.getEmail()));
         boolean phoneExists = model.getFilteredPersonList().stream()
                 .anyMatch(person -> person.getPhone().equals(toAdd.getPhone()));
-        boolean githubExists = model.getFilteredPersonList().stream()
+        boolean githubExists = !toAdd.getGithub().value.equals("No Github assigned")
```
Comment (crmlatte) [inline src/main/java/tassist/address/logic/commands/AddCommand.java:85]: Thx for updating the checks accurately

**Review by crmlatte — CHANGES_REQUESTED** [review]
Just a lil change in the string at Edit command! everything else is g

File: src/test/java/tassist/address/logic/commands/AddCommandTest.java [hunk 3]
```diff
@@ -115,6 +116,30 @@ public void execute_existingGithub_throwsCommandException() {
         assertThrows(CommandException.class, AddCommand.MESSAGE_EXISTING_GITHUB, () -> addCommand.execute(modelStub));
     }
 
+    @Test
```
Comment (crmlatte) [inline src/test/java/tassist/address/logic/commands/AddCommandTest.java:119]: nice testing

**Review by crmlatte — APPROVED** [review]
LGTM changes r g

**Review by Casielim — APPROVED** [review]
Yepp, looks good to me😁
